In [1]:
%load_ext autoreload
%autoreload 2
import torch
from torch import nn


/system/apps/userenv/beck/rwkv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## Understand single operations inside RWKV model

### Time shift operation

In [2]:
zp = nn.ZeroPad2d((0, 0, 1, -1))

In [3]:
t = torch.randn(2, 10, 5)
t

tensor([[[ 0.8484,  0.1798, -0.1841, -1.8499,  0.7515],
         [-1.1345, -0.7117, -0.3316,  0.4247,  1.4442],
         [ 1.3842, -1.8837,  0.6110,  0.5543,  1.4463],
         [ 2.8151,  0.7140, -0.9191, -1.0342, -0.6735],
         [ 0.1051,  1.6497, -1.1098,  0.6712,  0.4947],
         [ 1.2563, -0.6324, -0.5824, -0.1180, -1.8749],
         [ 1.3625, -0.0541, -0.2725,  3.1962, -1.4604],
         [-1.7580,  1.2531,  1.4149, -0.0412, -0.9744],
         [ 0.1492, -1.0672, -0.0570, -0.9744,  0.0480],
         [-0.9248,  0.4874, -0.5438, -1.4635,  0.5503]],

        [[-0.2822, -0.5515,  0.8484, -0.7601, -2.3858],
         [ 1.1154,  0.9619, -1.0014, -0.0994, -0.4242],
         [ 0.1656,  0.0472, -0.2683,  0.4059, -1.6349],
         [-0.1632, -0.0186,  2.0938,  0.0820, -0.2877],
         [ 0.6147,  0.0863, -0.6618,  1.0508, -1.2894],
         [ 2.3419, -0.2682, -0.7621,  0.0916,  0.5527],
         [ 0.3534, -0.5199, -1.8081,  1.0652,  1.1395],
         [ 1.3066,  0.8099,  0.8896,  0.3350, 

In [4]:
zp(t).shape

torch.Size([2, 10, 5])

In [5]:
zp(t)

tensor([[[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.8484,  0.1798, -0.1841, -1.8499,  0.7515],
         [-1.1345, -0.7117, -0.3316,  0.4247,  1.4442],
         [ 1.3842, -1.8837,  0.6110,  0.5543,  1.4463],
         [ 2.8151,  0.7140, -0.9191, -1.0342, -0.6735],
         [ 0.1051,  1.6497, -1.1098,  0.6712,  0.4947],
         [ 1.2563, -0.6324, -0.5824, -0.1180, -1.8749],
         [ 1.3625, -0.0541, -0.2725,  3.1962, -1.4604],
         [-1.7580,  1.2531,  1.4149, -0.0412, -0.9744],
         [ 0.1492, -1.0672, -0.0570, -0.9744,  0.0480]],

        [[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [-0.2822, -0.5515,  0.8484, -0.7601, -2.3858],
         [ 1.1154,  0.9619, -1.0014, -0.0994, -0.4242],
         [ 0.1656,  0.0472, -0.2683,  0.4059, -1.6349],
         [-0.1632, -0.0186,  2.0938,  0.0820, -0.2877],
         [ 0.6147,  0.0863, -0.6618,  1.0508, -1.2894],
         [ 2.3419, -0.2682, -0.7621,  0.0916,  0.5527],
         [ 0.3534, -0.5199, -1.8081,  1.0652, 

In [6]:
zp(t)[0, 1, :]

tensor([ 0.8484,  0.1798, -0.1841, -1.8499,  0.7515])

In [7]:
t[0, 0, :]

tensor([ 0.8484,  0.1798, -0.1841, -1.8499,  0.7515])

### Init of time_first 

In [8]:
attention_dim = 10
zigzag = torch.tensor([(i + 1) % 3 - 1
                       for i in range(attention_dim)]) * 0.5

In [9]:
zigzag

tensor([ 0.0000,  0.5000, -0.5000,  0.0000,  0.5000, -0.5000,  0.0000,  0.5000,
        -0.5000,  0.0000])